beam:
  energy: 10.2505
  vector: {azimuth: 119., polar_angle: 90.}
detectors:
  default:
    pixels:
      columns: 1250
      rows: 750
      size: [0.1, 0.1]
    buffer: [0.2, 0.2]
    transform:
      tilt: [0.0, 0.0, 0.0]
      translation: [0.0, 0.0, 0.0]
oscillation_stage:
  chi: 0.0
  translation: [0.0, 0.0, 0.0]
