#!/bin/bash

SCRIPT_DIR="$( cd "$(dirname "$0")" ; pwd -P )"
export FONTCONFIG_PATH="${SCRIPT_DIR}/../etc/fonts"
export FONTCONFIG_FILE="${SCRIPT_DIR}/../etc/fonts/fonts.conf"

"${SCRIPT_DIR}/python" "${SCRIPT_DIR}/run-hexrdgui.py" "$@"
