# We need a .txt extension for wix
file(COPY_FILE "${CMAKE_CURRENT_LIST_DIR}/../LICENSE" "${CMAKE_CURRENT_LIST_DIR}/LICENSE.txt")

set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_LIST_DIR}/LICENSE.txt")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "hexrdgui")
set(CPACK_PACKAGE_DESCRIPTION_FILE "description.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Qt5 PySide2 based HEXRD GUI")
set(CPACK_PACKAGE_EXECUTABLES "hexrdgui" "HEXRDGUI")
set(CPACK_PACKAGE_NAME "HEXRDGUI")
set(CPACK_PACKAGE_VENDOR "Kitware")
set(CPACK_PACKAGE_VERSION "$ENV{VERSION}")
set(CPACK_PACKAGE_VERSION_MAJOR "$ENV{VERSION_MAJOR}")
set(CPACK_PACKAGE_VERSION_MINOR "$ENV{VERSION_MINOR}")
set(CPACK_PACKAGE_VERSION_PATCH "$ENV{VERSION_PATCH}")
set(CPACK_PACKAGE_FILE_NAME "${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION}")
set(CPACK_INSTALL_COMMANDS "python package.py -h $ENV{HEXRD_PACKAGE_CHANNEL} -o $ENV{HEXRDGUI_OUTPUT_FOLDER}" )
set(CPACK_INSTALLED_DIRECTORIES "${CMAKE_CURRENT_LIST_DIR}/package;/")

if (APPLE)
  set(CPACK_GENERATOR "DragNDrop")
  # AppleScript currently doesn't work on github actions
  #set(CPACK_DMG_DS_STORE_SETUP_SCRIPT "${CMAKE_CURRENT_LIST_DIR}/darwin/CMakeDMGSetup.scpt")
  set(CPACK_DMG_DS_STORE "${CMAKE_CURRENT_LIST_DIR}/darwin/.DS_Store")
  set(CPACK_DMG_BACKGROUND_IMAGE "${CMAKE_CURRENT_LIST_DIR}/darwin/CMakeDMGBackground.tif")

  # Needed to find CoreServices
  if(NOT ENV{CPACK_OSX_SYSROOT})
    set(CPACK_OSX_SYSROOT $ENV{CPACK_OSX_SYSROOT})
  endif()
elseif(WIN32)
  set(CPACK_GENERATOR "WIX;ZIP")
  set(CPACK_WIX_PROPERTY_ARPURLINFOABOUT "https://github.com/HEXRD/hexrdgui")

  set(CPACK_WIX_PROPERTY_ARPCONTACT "hexrd@kitware.com")

  set(CPACK_WIX_PROPERTY_ARPCOMMENTS
    "Qt5 PySide2 based HEXRD GUI."
    )

  set(CPACK_WIX_PRODUCT_ICON
    "@CMAKE_CURRENT_LIST_DIR@/hexrd.ico"
    )

  set(CPACK_WIX_UI_BANNER
    "@CMAKE_CURRENT_LIST_DIR@/hexrd_logo.png"
    )

  set(CPACK_WIX_UI_DIALOG
    "@CMAKE_CURRENT_LIST_DIR@/hexrd_logo.png"
    )

  set(CPACK_WIX_UPGRADE_GUID "5F369ED0-05D7-4CBA-B533-D1A1B3F445C3")
  set(CPACK_WIX_TEMPLATE "${CMAKE_CURRENT_LIST_DIR}/windows/WIX.template.in")
  # We set this because it normally defaults to CMAKE_SIZEOF_VOID_P, but we aren't
  # running CMake here!
  set(CPACK_WIX_SIZEOF_VOID_P 8)
  set(CPACK_PACKAGE_INSTALL_DIRECTORY "HEXRDGUI")
  set(CPACK_CREATE_DESKTOP_LINKS "HEXRDGUI" "HEXRDGUI")
else()
  set(CPACK_GENERATOR "TGZ")
endif()
