#!/usr/bin/env bash
SCRIPT_DIR="$( cd "$(dirname "$0")" ; pwd -P )"
echo $SCRIPT_DIR
export QT_PLUGIN_PATH=$SCRIPT_DIR/../Resources/plugins
$SCRIPT_DIR/../Resources/bin/python $SCRIPT_DIR/../Resources/bin/hexrdgui $@
