package:
  name: hexrdgui
  version: {{ environ.get('GIT_DESCRIBE_TAG', environ['GIT_FULL_HASH'][:8]) }}

source:
  path: ../

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  entry_points:
    - hexrdgui = hexrdgui.main:main

requirements:
  build:
    - python {{ python }}                    # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python {{ python }}
    - setuptools
    - setuptools_scm

  run:
    - python
    - fabio
    - hexrd=={{ hexrd_version }}
    - matplotlib-base
    - Pillow
    - pyhdf
    # This next one is needed to fix the app name on Mac
    - pyobjc-framework-cocoa  # [osx]
    # Lock the PySide6 version to be less than 6.8 for Mac.
    # This is because Qt 6.8 has some crashing issue we need
    # to resolve. This issue is tracked in:
    # https://github.com/HEXRD/hexrdgui/issues/1931
    - pyside6<6.8  # [osx]
    - pyside6  # [not osx]
    - pyyaml
    - silx-base

test:         # [build_platform == target_platform]
  imports:
    - hexrdgui

about:
  home: https://github.com/HEXRD/hexrdgui
  license: BSD
  license_family: BSD
  summary: "Qt6 PySide6 based HEXRD GUI"
