{% set python_min = "3.11" %}

package:
  name: hexrdgui
  version: {{ environ.get('GIT_DESCRIBE_TAG', environ['GIT_FULL_HASH'][:8]) }}

source:
  path: ../

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  noarch: python
  entry_points:
    - hexrdgui = hexrdgui.main:main

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools_scm

  run:
    - python >={{ python_min }}
    - fabio
    - hexrd=={{ hexrd_version }}
    - matplotlib-base
    - Pillow
    - pyhdf
    # This next one is needed to fix the app name on Mac
    - pyobjc-framework-cocoa  # [osx]
    - pyside6
    - pyyaml
    - silx-base

test:         # [build_platform == target_platform]
  imports:
    - hexrdgui

about:
  home: https://github.com/HEXRD/hexrdgui
  license: BSD
  license_family: BSD
  summary: "Qt6 PySide6 based HEXRD GUI"
