package:
  name: hexrdgui
  version: {{ environ.get('GIT_DESCRIBE_TAG', environ['GIT_FULL_HASH'][:8]) }}

source:
  path: ../

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  entry_points:
    - hexrdgui = hexrd.ui.main:main

requirements:
  build:
    - python=3.8
    - setuptools
    - setuptools_scm

  run:
    - python
    - pyside2
    - Pillow
    - matplotlib
    - importlib_resources
    - fabio
    - pyyaml
    - hexrd
    - pyhdf
    - silx

test:
  imports:
    - hexrd.ui

about:
  home: https://github.com/HEXRD/hexrdgui
  license: BSD
  license_family: BSD
  summary: "Qt5 PySide2 based HEXRD GUI"
